#!/usr/bin/env python
import sys
import db_connection
from review_cards import review_cards
from new_card import new_card
from new_cards import new_cards

conn, cursor = db_connection.connect()

if len(sys.argv) == 1:
   review_cards(conn, cursor)
elif sys.argv[1] == '-n':
    new_card(conn, cursor, False)
elif sys.argv[1] == '-n2':
    new_card(conn, cursor, True)
elif sys.argv[1] == '-N':
    new_cards(conn, cursor, False)
elif sys.argv[1] == '-N2':
    new_cards(conn, cursor, True)
else:
    print('Usage info coming soon.')

print('Kbai')

db_connection.disconnect(conn, cursor)
